apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flight-tracker

resources:
  - ../../base
  - mysql-sealed-secret.yaml
  - api-sealed-secret.yaml

# Image tags will be updated by CI/CD
images:
  - name: ghcr.io/halitdincer/flight-tracker-api
    newTag: latest
  - name: ghcr.io/halitdincer/flight-tracker-web
    newTag: latest
